### PR TITLE
Metadata cache

### PR DESCRIPTION
**Pull request by dantleech**
Adds caching for the metadata. Currently uses only the file cache.

Closes https://github.com/massiveart/MassiveSearchBundle/issues/23

### CODE REVIEW

**Comment by chirimoya** [comment]
ping

**Comment by dantleech** [comment]
Added a benchmark, the cache actually has not a very big effect on performance. Reading XML files seems to be extremely fast already:

````bash
Running benchmark suite

Massive\Bundle\SearchBundle\Tests\Benchmark\MetadataFactoryBenchmark
..

Generating reports...

>> console_table >>

Massive\Bundle\SearchBundle\Tests\Benchmark\MetadataFactoryBenchmark#benchFactoryWithoutCache(): Retireve without cache
+-----+--------------+-------+-------------+-------------+-------------+
| run | revs         | iters | avg_time    | min_time    | max_time    |
+-----+--------------+-------+-------------+-------------+-------------+
| 1   | 76,260.07rps | 250   | 0.00000892s | 0.00000691s | 0.00002122s |
+-----+--------------+-------+-------------+-------------+-------------+

Massive\Bundle\SearchBundle\Tests\Benchmark\MetadataFactoryBenchmark#benchFactoryWithCache(): Retireve metadata with cache
+-----+--------------+-------+-------------+-------------+-------------+
| run | revs         | iters | avg_time    | min_time    | max_time    |
+-----+--------------+-------+-------------+-------------+-------------+
| 1   | 91,180.52rps | 250   | 0.00000863s | 0.00000691s | 0.00002503s |
+-----+--------------+-------+-------------+-------------+-------------+

Done (0.642143)
````

**Comment by dantleech** [comment]
Remove the benchmark stuff from the branch and put it in another PR.

**Pull request merged**
