### PR TITLE
Extract search in some more methods to ease extending

### PR DESCRIPTION
**Pull request by gisostallenberg**

### CODE REVIEW

**Comment by alexander-schranz** [comment]
Can you do the same for the LuceneAdapter?

**Comment by gisostallenberg** [comment]
> Can you do the same for the LuceneAdapter?

I could, but because of the inner workings it is not really possible to have the same method signatures.  Is that ok?

**Comment by alexander-schranz** [comment]
@gisostallenberg you mean the method will  have other arguments? Yes thats okay.

**Comment by gisostallenberg** [comment]
@alexander-schranz I think this ok this way.

**Pull request merged**
