### PR TITLE
Add app config/massive-search dir as metadataPath

### LINKED ISSUE #137: Indexation of App Bundle in Symfony 4
I use  Sulu for a couple of weeks now and I tried to index an entity of my project in App\Entity (App\Entity\Commune).
I put the Commune.xml in src/Resources/config/massive-search/Commune.xml
But when I execute php bin/console massive:search:reindex, nothing happens.

It seems that the explored paths for metadatas are only from bundle : 
`$container->getParameter('kernel.bundles')`

And so when I dump the paths form `getBundleMappingPaths` (DependencyInjection/MassiveSearchExtension.php), I only get this :

> array:3 [
  "Sulu\Bundle\ContactBundle\Entity" => "/Users/me/Documents/WebProjets/myproject/vendor/sulu/sulu/src/Sulu/Bundle/ContactBundle/Resources/config/massive-search"
  "Sulu\Bundle\MediaBundle\Entity" => "/Users/me/Documents/WebProjets/myproject/vendor/sulu/sulu/src/Sulu/Bundle/MediaBundle/Resources/config/massive-search"
  "Sulu\Bundle\CategoryBundle\Entity" => "/Users/me/Documents/WebProjets/myproject/vendor/sulu/sulu/src/Sulu/Bundle/CategoryBundle/Resources/config/massive-search"
]

Is there a way to add AppBundle or is it a limitation which obliges to use a bundle to index entities ?
Thank you very much :)

### PR DESCRIPTION
**Pull request by alexander-schranz**
fixes #137

### CODE REVIEW

**Comment by cedricvazille** [comment]
It was almost that :
$metadataPaths["App\Entity"] = $container->getParameter('kernel.project_dir') . '/config/massive-search';

This resolve my problem and now my Entity is well indexed, thank you very much 👍

**Comment by cedricvazille** [comment]
Be carefull, I change your $metadataPaths[] by $metadataPaths["App\Entity"]
This produces a :
0 => "/Users/me/Documents/WebProjets/myproject/config/massive-search" 
instead of :
"App\Entity" => "/Users/me/Documents/WebProjets/myproject/config/massive-search"

**Comment by alexander-schranz** [comment]
@cedricvazille  you are correct did update the logic.

**Comment by cedricvazille** [comment]
Your last version works great for me !
Thank you again :)

**Pull request merged**
